#################################
### Install Hugin deb package ###
#################################

- name: Copy the hugin deb package
  copy:
    src: files/hugin-2019.0.0.0-beta1-Ubuntu-16.04.deb
    dest: /tmp/hugin-2019.0.0.0-beta1-Ubuntu-16.04.deb

- name: Install hugin deb package
  apt:
    deb: /tmp/hugin-2019.0.0.0-beta1-Ubuntu-16.04.deb
    install_recommends: no

#######################################
### Install Hugin in our virtualenv ###
#######################################

- name: Link to hsi.py
  file:
    src: /usr/lib/python3/dist-packages/hsi.py
    dest: /home/opv/venvs/opv/lib/python3.5/site-packages/hsi.py
    state: link

- name: Link to _hsi.so
  file:
    src: /usr/lib/python3/dist-packages/_hsi.so
    dest: /home/opv/venvs/opv/lib/python3.5/site-packages/_hsi.so
    state: link
